export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const RQUEST_ROBOTS_PENDING = 'RQUEST_ROBOTS_PENDING'
export const RQUEST_ROBOTS_SUCCESS = 'RQUEST_ROBOTS_SUCCESS'
export const RQUEST_ROBOTS_FAILED = 'RQUEST_ROBOTS_FAILED'